import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/src/components/layout/Header";
import RecoilProvider from "@/src/components/providers/RecoilProvider";
import NextuiProvider from "@/src/components/providers/NextuiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trip Trek",
  description: "Generated by create next app",
  icons: [
    {
      url: "/favicon.png",
      sizes: "32x32",
      type: "image/png"
    }
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <NextuiProvider>
          <RecoilProvider>
              <Header />
              {children}
          </RecoilProvider>
        </NextuiProvider>
      </body>
    </html>
  );
}
