import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/src/components/layout/Header";
import RecoilProvider from "@/src/components/providers/RecoilProvider";
import NextuiProvider from "@/src/components/providers/NextuiProvider";
import NextAuthProvider from "@/src/components/providers/NextAuthProvider";
import { getServerSession } from "next-auth";
import { getCurrentUser } from "@/src/actions";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trip Trek",
  description: "Generated by create next app",
  icons: [
    {
      url: "/favicon.png",
      sizes: "32x32",
      type: "image/png"
    }
  ]
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  const currentUser = await getCurrentUser();

  return (
    <html lang='en' suppressHydrationWarning>
      <body >
        <NextAuthProvider session={session}>
          <NextuiProvider>
            <RecoilProvider>
              <ToastContainer position="top-center" theme="dark" autoClose={3000} />
              <Header currentUser={currentUser} />
              {children}
            </RecoilProvider>
          </NextuiProvider>          
        </NextAuthProvider>
      </body>
    </html>
  );
}
